version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports: ['5432:5432']
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
volumes:
  postgres_data:




  